#pragma once

#include <stdint.h>

typedef enum {
    ADC_REGISTER_STATUS = 0x00,
    ADC_REGISTER_MUX = 0x01,
    ADC_REGISTER_ADCON = 0x02,
    ADC_REGISTER_DRATE = 0x03,
    ADC_REGISTER_IO = 0x04,
    ADC_REGISTER_OFC0 = 0x05,
    ADC_REGISTER_OFC1 = 0x06,
    ADC_REGISTER_OFC2 = 0x07,
    ADC_REGISTER_FSC0 = 0x08,
    ADC_REGISTER_FSC1 = 0x09,
    ADC_REGISTER_FSC2 = 0x0A,
} AdcRegisters;
