M48
; DRILL file {KiCad 8.0.3} date 2024-07-08T02:20:14+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-08T02:20:14+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X1.8917Y-2.4823
X1.8917Y-6.1791
X5.5886Y-2.4823
X5.5886Y-6.1791
T2
X2.302Y-4.3512
M30
