M48
; DRILL file {KiCad 7.0.10} date 西元2024年05月28日 (週二) 11時55分38秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-28T11:55:38+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.8917Y-2.4823
X1.8917Y-6.1791
X5.5886Y-2.4823
X5.5886Y-6.1791
M30
